name:
    ddc

channels:
    - pytorch
    - conda-forge

dependencies:
    - python=3.9
    - pip
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - pytorch
    - tqdm
    - ipykernel
    - jupyter
    - jupytext
     
    - pip:
        - --editable .
        - pydove
